language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t michaelirl/docker-react -f Dockerfile.dev .

script:
  -docker run michaelirl/docker-react npm run test -- --watchAll=false