language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t michaelirl/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true michaelirl/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Docker-React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-472867233942"
  bucket_path: "docker-react"
  on:
    branch: master

access_key_id:
  secure: $AWS_ACCESS_KEY
secret_access_key:
  secure: "$AWS_SECRET_KEY"